class Homeworks {
  static List<String> Names = [
    "Fashion Login",
    "Dress Store",
    "Sport Page",
    "Insta Explore",
    "Sliver Bar",
    "Burger Cafe",
    "Coffee Store",
    "Project",
    "Rent Car",
    "Food cafe",
    "Find Number",
    "New One",
    "Telegram",
    "Expansion",
    "Font Page",
    "Quiz Game",
    "Tesla Page",
    "Messenger P",
    "Ui PAge",
    "Indigo Page",
    "Step Page",
    "Login Page",
    "Homework",
    "Barber Shop",
    "Hotel",
    "New Ui",
  ];
  static List<String> Definition = [
    "First ui",
    "FW19",
    "Sports",
    "Explore",
    "Sliver AppBar",
    "Grid View",
    "Coffee shop ui",
    "Project",
    "Rent Car",
    "Border container",
    "Find Number",
    "New One",
    "Telegram",
    "Expansion",
    "Font Page",
    "Quiz Game",
    "Tesla Page",
    "Messenger P",
    "UiPage",
    "Indigo Page",
    "Step Page",
    "Login Page",
    "Homework",
    "Barber Shop",
    "Hotel",
    "New Ui",
  ];
  static List<String> Info = [
    "Design",
    "Design",
    "Alignment",
    "Row & Column",
    "Sliver",
    "Grid",
    "Design",
    "Design",
    "Design",
    "Design",
    "For Logic",
    "New one",
    "Telegram",
    "Expansion",
    "Drawer",
    "Login Page",
    "Tesla Page",
    "Messenger P",
    "UiPage",
    "Indigo Page",
    "Step Page",
    "Quiz Game",
    "Homework",
    "Barber Shop",
    "Hotel",
    "New Ui",
  ];
}
